# Generated by Django 5.0.6 on 2024-05-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255, null=True)),
                ('success', models.BooleanField()),
                ('message', models.CharField(max_length=255, null=True)),
                ('clazz', models.IntegerField(db_column='class', null=True)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('request_timestamp', models.DateTimeField(null=True)),
                ('response_timestamp', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'ai_analysis_log',
            },
        ),
    ]
